### ISSUE TITLE
Update[S,E] vs Recovery[A,D,S]

### ISSUE THREAD

**Issue by dispalt** [nokia/akka-typed-persistence#8]
Why not make allow the Update function have access to the context as well?

For instance in this example, https://github.com/nokia/akka-typed-persistence/blob/ac682e0914924823a2a00c79d5331e6cff57539b/src/test/scala/com/nokia/ntp/ct/persistence/DeploymentSpec.scala#L58 It practically doesn't make sense to treat a ref as an event.  Since it changes from program invocation to program invocation right?  Now obviously this is a test so it's not really meant to be practical, but wouldn't it be better to give the update method access to the context so then you could treat the forking a child actor as an event save, like below?  

```scala

implicit val parentUpdater: Update[ParentState, at.ActorRef[Mesg]] =
    Update.instance((_, e, ctx) => e match {
 case Uninitialized => 
   val childRef = child(pid).deployInto(ctx.ctx)
  Initialized(childRef)
}

...


 case Uninitialized =>
   ctx.apply(childRef, sync = true)
```

**Comment by dilation** [comment]
What you are saying, makes sense. However, I wouldn't want the  `Update` implementation to deploy child actors while _computing_ the next state. Ideally it would be a pure function.

I imagine that the general pattern would be something like this:

```scala
for {
  event <- createTheEvent() // possibly also execute some side-effects
  state <- ctx.apply(event) // persist the event
  state <- otherSideEffects() // if other side-effects need to be performed (e.g., sending an ack)
} yield state
```

So we can perform the side-effects before and/or after the persistence. I'd like to keep them out of the update itself ... it just feels wrong to do them during.

However, a really good solution would be to _include these side-effects in the operations_. That is, the `PersistenceApi`  could contain (besides the current `apply`, `stop`, ...) operations like `spawnChild`. Then we could avoid these side-effects entirely (because they would be incorporated into the DSL). I'd like to experiment with this approach, if I'll have time. (See this, for a DSL which includes such operations: https://github.com/akka/akka/pull/22087. Although it doesn't have persistence yet.)

**Comment by dispalt** [comment]
Thanks for the explanation, makes sense.  Also he started a repo playing with the typed api. https://github.com/rkuhn/akka-typed-process-demo

**Comment by dispalt** [comment]
@dilation btw, I like including spawn/fork in the algebra, I think it makes a lot of sense.
